name: test_windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up ISPC 1.23
      uses: ScatteredRay/install-ispc-action@main
      with:
        version: 1.23.0
        platform: windows
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt       
    - name: Test
      run: |
        cd tests
        setx OPENCL_CTX "0:0"
        python test.py
