name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: streamhpc/opencl-sdk-base:ubuntu-18.04-20220127
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.14'
    - name: Install dependencies
      run: |
        python -m ensurepip --upgrade
        pip install -r requirements.txt
        apt update
        apt install snapd
        snap install ispc
    - name: Running tests
      run: |
        cd tests
        OPENCL_CTX='0:0' python test.py
