name: Linux test
on: [push]
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ispc
        python -m ensurepip --upgrade
        pip install -r requirements.txt
        sudo apt-get install -y libvulkan-dev mesa-vulkan-drivers libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libgles2-mesa-dev
        cd slangpy
        pip install .
    - name: Running tests
      run: |
        cd tests
        python test.py
