name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.14'
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y snapd ocl-icd-opencl-dev libpocl2 mesa-opencl-icd
        sudo snap install ispc
        python -m ensurepip --upgrade
        pip install -r requirements.txt
    - name: Running tests
      run: |
        cd tests
        OPENCL_CTX='0:0' python test.py
